Added new default command
WaterdogPE/WaterdogPE pull request #82
Opened 2021-04-11 17:51 UTC by VazziDE

Added /wdplugins to list all the plugins which are used on the proxy.

2021-04-11 22:54 UTC, TobiasG-DE commented
That is not really the recommended way for using Lists.. you might want to consider String.join instead of some hacky .toString().replace() hack. Besides that, I don't think such a command is that useful, especially without displaying the version of the plugin. Overall I doubt the usability of this command, I don't get why people need a plugins command any way, because they should always know what plugins they are running. 
This command does not provide any additional information, for example about the load status of a plugin. Opinion @Alemiz112 ?

2021-04-12 06:13 UTC, Alemiz112 requested changes

2021-04-12 06:13 UTC, Alemiz112 commented on src/main/java/dev/waterdog/command/defaults/PluginsCommand.java
> +
Extra spacing here.

2021-04-12 06:13 UTC, Alemiz112 commented on src/main/java/dev/waterdog/command/defaults/PluginsCommand.java
> +package dev.waterdog.command.defaults;
I think it would be nice if all files would contain copyright header.

2021-04-12 06:13 UTC, Alemiz112 commented on src/main/java/dev/waterdog/command/defaults/PluginsCommand.java
> +
Another extra spacing.

2021-04-12 06:13 UTC, Alemiz112 commented on src/main/java/dev/waterdog/command/defaults/PluginsCommand.java
> +        String pluginsformat = PluginsListArr.toString().replace("[", "").replace("]", "");
This isnt valid way of how to join string array/list. Use `String.join()` instead.

2021-04-12 06:18 UTC, Alemiz112 commented
I agree with Tobias that this command itself is useless. Proxy does not support plugin reloading so I dont see here any point here.
If you really want to merge this, command should give user more details about the plugin - loaded or enabled,  plugin version ...

2021-04-12 08:39 UTC, TobiasG-DE commented
I believe we can close this PR, the OP can reopen once proper changes were made and we get a specification on the actual benefit this command should come with.

2021-04-12 08:39 UTC, closed without merging